# task list extracted from role "geerlingguy.kubernetes"
---
- hosts: all
  vars:
    kubernetes_yum_arch: x86_64
    kubernetes_packages:
      - name: kubectl
        state: present
    _kubernetes_mirror: https://mirrors.aliyun.com/kubernetes
  tasks:
    - name: Ensure Kubernetes repository exists.
      yum_repository:
        name: kubernetes
        description: Kubernetes
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        baseurl: {{ _kubernetes_mirror }}/yum/repos/kubernetes-el7-{{ kubernetes_yum_arch }}
        gpgkey:
          - {{ _kubernetes_mirror }}/yum/doc/yum-key.gpg
          - {{ _kubernetes_mirror }}/yum/doc/rpm-package-key.gpg

    - name: Add Kubernetes GPG keys.
      rpm_key:
        key: "{{ item }}"
        state: present
      register: kubernetes_rpm_key
      with_items:
        - {{ _kubernetes_mirror }}/yum/doc/yum-key.gpg
        - {{ _kubernetes_mirror }}/yum/doc/rpm-package-key.gpg

    - name: Make cache if Kubernetes GPG key changed.
      command: "yum -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
      when: kubernetes_rpm_key is changed
      args:
        warn: false
    - name: Install Kubernetes packages.
      package:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ kubernetes_packages }}"
